### ISSUE TITLE
Possible bug found in TCP receive

### ISSUE THREAD

**Issue by zarazek** [GaloisInc/HaNS#16]
Possible bug in master branch at [src/Hans/Tcp/RecvWindow.hs:77](https://github.com/GaloisInc/HaNS/blob/master/src/Hans/Tcp/RecvWindow.hs#L77):
There is:
```
case trimSeg (fromTcpSeqNum (segEnd x - segStart y)) x of
```
Shouldn't it be:
```
case trimSeg (fromTcpSeqNum (segEnd x - segStart y)) y of
``` 
?
And later:
```
Just x' -> [x', y]
```
Shouldn't it be:
```
Just y' -> [x, y']
```
?

**Comment by elliottt** [comment]
This is intended. The idea is that you're trimming the segment `x` to remove the overlap with `y`. So, it trims from the point where they overlap, shrinking it down so that `y` doesn't have to be modified. This is also why `y` is returned unchanged.

**Comment by zarazek** [comment]
Sure, but if you have two overlapping segments: former x and latter y, to remove overlap you would want to trim back of x or front of y, not front of x.

**Comment by zarazek** [comment]
Also, if y is fully contained in x, `trimSeg ... y` would return `Nothing`, and you want to handle this case by returning `[x]`, not throwing an error.

**Comment by elliottt** [comment]
You're right, it should be trimming from the front of y. I'll push a fix, thanks for the report!
