### ISSUE TITLE
Installation failed due to "tcp-test-client"

### ISSUE THREAD

**Issue by izgzhen** [GaloisInc/HaNS#4]
When I `halvm-cabal install`, it failed like this after installing some packages:

	Resolving dependencies...
	Configuring hans-2.4.0.0...
	cabal: No 'main-is' field found for executable tcp-test-client
	Failed to install hans-2.4.0.0
	cabal: Error: some packages failed to install:
	hans-2.4.0.0 failed during the configure step. The exception was:
	ExitFailure 1

**Comment by izgzhen** [comment]
After I do some little modification to the cabal file, another installation failure happens:

configure: WARNING: unrecognized options: --with-compiler, --with-hc-pkg, --with-gcc
	cabal: Missing dependency on a foreign library:
	* Missing (or bad) header file: HsUnix.h
	This problem can usually be solved by installing the system package that
	provides this library (you may need the "-dev" version). If the library is
	already installed but in a non-standard location then you can use the flags
	--extra-include-dirs= and --extra-lib-dirs= to specify where it is.
	If the header file does exist, it may contain errors that are caught by the C
	compiler at the preprocessing stage. In this case you can re-run configure
	with the verbosity flag -v3 to see the error messages.
	Failed to install unix-2.7.1.0
	cabal: Error: some packages failed to install:
	hans-2.4.0.0 depends on unix-2.7.1.0 which failed to install.
	network-2.6.0.2 depends on unix-2.7.1.0 which failed to install.
	unix-2.7.1.0 failed during the configure step. The exception was:
	ExitFailure 1

**Comment by elliottt** [comment]
This issue should be fixed now.
